<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td><h3 class="head-dashboard">Promotale</h3></td>
        </tr>
        </tbody>
    </table>
</div>
<div class="dashboard-container promotale">
    <p class="switcher">
        <i class="dashboard-promotale-icon"></i>
        Dashboard
    </p>
    <table cellspacing="25" width="100%">
        <tbody>
            <tr>
                <td width="50%">
                    <!--Campania cea mai eficienta-->
                    <div class="entry-edit">
                        <div class="tmec entry-edit-head ">
                            <h4>
                                <i class="icon icon-star"></i>
                                The most effective campaign
                            </h4>
                        </div>
                        <fieldset class="np">
                            <div class="grid np">
                                <table cellspacing="0" style="border:0;">
                                    <thead>
                                        <tr class="headings">
                                            <th class="no-link">
                                                <span class="nobr">Name</span>
                                            </th>
                                            <th class="no-link">
                                                <span class="nobr">Date start</span>
                                            </th>
                                            <th class="no-link">
                                                <span class="nobr">Date expire</span>
                                            </th>
                                            <th class="no-link last">
                                                <span class="nobr">Website</span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="even pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                    </div>
                    
                    <!--Promotii active-->
                    <div class="entry-edit">
                        <div class="entry-edit-head">
                            <h4>
                                <i class="icon icon-checkmark"></i>
                                Active promotions
                            </h4>
                        </div>
                        <fieldset class="np">
                            <div class="grid np">
                                <table cellspacing="0" style="border:0;">
                                    <thead>
                                        <tr class="headings">
                                            <th class="no-link">
                                                <span class="nobr">Name</span>
                                            </th>
                                            <th class="no-link">
                                                <span class="nobr">Date start</span>
                                            </th>
                                            <th class="no-link">
                                                <span class="nobr">Date expire</span>
                                            </th>
                                            <th class="no-link last">
                                                <span class="nobr">Website</span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="even pointer" title="http://#">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="odd pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="even pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="odd pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="even pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="odd pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="even pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="odd pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="even pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                        <tr class="odd pointer">
                                            <td>Lorem ipsum promotion</td>
                                            <td>Mar 15, 2014</td>
                                            <td>Mar 15, 2014</td>
                                            <td>www.mywebsite.com</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                    </div>
                    
                </td>
                <td width="50%">
                    <div class="entry-edit statistics">
                        <div class="entry-edit-head">
                            <h4>
                                <i class="icon icon-chart"></i>
                                Statistics
                            </h4>
                            <p class="a-right">
                                Select range:
                                <select name="period" id="order-orders-period" onchange="changeDiagramsPeriod(this);"style="height:19px;">
                                    <option value="24h">Last 24 Hours</option>
                                    <option value="7d">Last 7 Days</option>
                                    <option value="1m">Current Month</option>
                                    <option value="1y">YTD</option>
                                    <option value="2y">2YTD</option>
                                </select>
                            </p>
                        </div>
                        <div class="promotale-statistics">
                           <p style="width:587px;height:300px; margin:0 auto;">
                               <img src="http://magento-promotale.nginx.dev54.zitec.ro/index.php/admin/dashboard/tunnel/key/fb3908233fea01c1afb477514cc41a8f/?ga=YTo5OntzOjM6ImNodCI7czoyOiJsYyI7czozOiJjaGYiO3M6Mzk6ImJnLHMsZjRmNGY0fGMsbGcsOTAsZmZmZmZmLDAuMSxlZGVkZWQsMCI7czozOiJjaG0iO3M6MTQ6IkIsZjRkNGIyLDAsMCwwIjtzOjQ6ImNoY28iO3M6NjoiZGI0ODE0IjtzOjM6ImNoZCI7czoxNjoiZTpBQUFBQUFBQUFBZi5BQSI7czo0OiJjaHh0IjtzOjM6IngseSI7czo0OiJjaHhsIjtzOjgxOiIwOnw0LzE5LzIwMTR8NC8yMC8yMDE0fDQvMjEvMjAxNHw0LzIyLzIwMTR8NC8yMy8yMDE0fDQvMjQvMjAxNHw0LzI1LzIwMTR8MTp8MHwxfDIiO3M6MzoiY2hzIjtzOjc6IjU4N3gzMDAiO3M6MzoiY2hnIjtzOjIyOiIxNi42NjY2NjY2NjY2NjcsNTAsMSwwIjt9&amp;h=42d9ca2fa337d5742672056d66887d00" alt="chart" title="chart">
                           </p>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>